### ISSUE TITLE
Update to pm5 please 

### ISSUE THREAD

**Issue by SR9GAMING** [Shock95/AuctionHouse#127]
### Issue description
I Want pm5

### Steps to reproduce the issue
1. ...
2. ...

### OS and versions
* PocketMine-MP:
* Plugin version: 
* Server OS:

### Error/Crash log (If available)

```

```

**Comment by UnknownNull** [comment]
> https://github.com/FieldDefaults/AuctionHouse-PM5

It has many bugs.  For example, you can pick up the item without buying it

**Comment by XackiGiFF** [comment]
> > https://github.com/FieldDefaults/AuctionHouse-PM5
> 
> It has many bugs. For example, you can pick up the item without buying it

I was fix it: https://github.com/XackiGiFF/AuctionHouse-PM5

Only one bug I can`t fix - no category view in GUI when i try `/ah category`
